---
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ldap
    image: bitnami/openldap
    pre_build_image: true
    groups:
      - sidecar
    env:
      LDAP_PORT_NUMBER: "1389"
      LDAP_ROOT: "dc=example,dc=org"
      LDAP_SKIP_DEFAULT_TREE: "yes"
    volumes:
      - "$PWD/molecule/default/testdata.ldif:/ldifs/testdata.ldif:ro"
    command: ""
    published_ports:
      - "1389:1389"
    networks:
      - name: molecule
  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: molecule

provisioner:
  name: ansible
